---
title: "R Notebook"
output: html_notebook
---




```{r}

vehicles<-read.csv("vehicles.csv")

vehdata<-data.frame(
  manufacturer=vehicles$make,model=vehicles$model,class=vehicles$VClass,
  fueltype=vehicles$fuelType,fueltype1=vehicles$fuelType1,fueltype2=vehicles$fuelType2,savespend=vehicles$youSaveSpend,
  citympg1=vehicles$city08,citympg2=vehicles$cityA08,
  combmpg1=vehicles$comb08,combmpg2=vehicles$combA08,
  hw1=vehicles$highway08,hw2=vehicles$highwayA08,
  co2.1=vehicles$co2TailpipeGpm,co2.2=vehicles$co2TailpipeAGpm,
  fuelcost1=vehicles$fuelCost08,fuelcost2=vehicles$fuelCostA08,
  year=vehicles$year)

head(vehdata)

```

```{r}
totaltype=unique(vehdata$fueltype)
makelist=unique(vehdata$manufacturer)

singlefuel=vehdata[vehdata$fueltype2=="",]

mixedfuel=vehdata[vehdata$fueltype2!="",]

singlefuel.avg=ddply(singlefuel,.(fueltype),summarize,savespend=mean(savespend),
   citympg=mean(citympg1),combmpg=mean(combmpg1),highwaympg=mean(hw1),
   co2=mean(co2.1),fuelcost=mean(fuelcost1))

mixedfuel.avg=ddply(mixedfuel,.(fueltype),summarize,savespend=mean(savespend),
  citympg=mean(c(citympg1,citympg2)),combmpg=mean(c(combmpg1,combmpg2)),
  highwaympg=mean(c(hw1,hw2)),co2=mean(c(co2.1,co2.2)),fuelcost=mean(c(fuelcost1,fuelcost2)))


fuel.avg=rbind(singlefuel.avg,mixedfuel.avg)


barplot(fuel.avg$savespend,main="Save/Spend on fuel costs in five years",horiz=TRUE,names.arg=fuel.avg$fueltype,las=1,beside=TRUE)
mpg=cbind(fuel.avg$combmpg,fuel.avg$citympg,fuel.avg$highwaympg)
mpg=t(mpg)
barplot(mpg,main="MPG for different fuels",xlab="fuels",col=c("darkblue","red","yellow"),beside=TRUE,names.arg=fuel.avg$fueltype,legend=c("combined MPG","city MPG","highway MPG"))

barplot(fuel.avg$co2,names.arg=fuel.avg$fueltype)
barplot(fuel.avg$fuelcost,names.arg=c(1:13))

```






```{r}
runApp("~/GitHub/Spr2017-proj2-grp7/doc/Yue Gao")
rsconnect::deployApp("YueGao_v1.Rmd")
 

```
```{r}

  temp=fuel.avg[fuel.avg$fueltype %in% stype,]
  temp2=temp$savespend
  barplot(temp2,
            main="Save/Spend on fuel costs in five years",
            horiz=TRUE,names.arg=temp$fueltype,las=1,beside=TRUE)
    
     
  output$mpg=renderPlot({
  temp=subset(fuel.avg,select=c(fueltype,combmpg,citympg,highwaympg))
  
  mpg=temp[temp$fueltype %in% stype,]
  mpg.m=subset(mpg,select=-fueltype)
  mpg.m=t(mpg.m)
  barplot(mpg.m,main="MPG for different fuels",xlab="fuels",
          col=c("darkblue","red","yellow"),beside=TRUE,names.arg=mpg$fueltype,
          legend=c("combined MPG","city MPG","highway MPG"))
})
  
  
  output$co2=renderPlot({
    temp=subset(fuel.avg,select = c(fueltype,co2))
    temp=temp[temp$fueltype %in% stype,]
    barplot(temp$co2,names.arg=temp$fueltype)
  })
  
  output$fuelcost=renderPlot({
    temp=subset(fuel.avg,select = c(fueltype,fuelcost))
    temp=temp[temp$fueltype %in% stype,]
    barplot(temp$fuelcost,names.arg=temp$fueltype)
  })
```

